services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

#  adminer:wq
#    image: adminer
#    restart: always
#    ports:
#      - 8090:8090

volumes:
  pgdata: